java: /root/software/openjdk-8u292-b10/bin/java
perl: /usr/bin/perl
python2:  /usr/local/Python-2.7.14/bin/python
python3:  /usr/local/Python-3.9.5/bin/python3
fastqc: /root/software/fastqc
trimmomatic:  /root/software/trimmomatic-0.36.jar
reseqtools: /root/software/iTools_Code/ReSeqTools
bwa:  /root/software/bwa-0.7.17/bwa
picard: /root/software/picard.jar
GATK3: /root/software/GenomeAnalysisTK.jar
GATK4: /root/software/gatk
varscan: /root/software/VarScan.v2.3.9.jar
samtools: /root/software/samtools-1.13/samtools
bedtools: /root/software/bedtools2/bin/bedtools
snakemake: /usr/local/Python-3.9.5/bin/snakemake
#############database###########################################
DNA:
  adapters_path: /home/database/DNA/RNA_fusion.fa
  bed: /home/database/DNA/DNA_Hotspot_sequence_V1.3_short.bed
  target_bed: /home/database/DNA/DNA_Hotspot_target_V1.3_short.bed
  ref: /home/database/DNA/hg19.fa
  zc_hotspots: /home/database/DNA/zc_hotspots_v1.2.txt
  canonical: /home/database/DNA/whole_ID_Canonical.txt
  hotspots: /home/database/DNA/hotspots_simple.txt
  black_list: /home/database/DNA/thyroid_amp_v1.4_black.list

#############RNA database###########################################
RNA:
  adapters_path:  /home/database/RNA/RNA_fusion.fa
  bed:  /home/database/RNA/fusion_ZC_new_v1.bed
  ref:  /home/database/RNA/fusion_ZC_new_v1.fasta
  fusion_anno_txt:  /home/database/RNA/fusion_ZC_new_anno_v1.txt
